#!/bin/bash
#
# Create a new script in my scripts collection

name=$1

if [ $# -eq 0 ]; then
  read -rp "Please provide a name for the script: " name
fi

cd "$SCRIPTS" || exit
touch "$name"
chmod +x "$name"
{
  echo "#!/bin/bash"
  echo "#"
  echo "#"
} >> "$name"
