#!/bin/bash
#
# Create a new note in the required format and save it in the specified directory

# Prompt the user for a filename
get_filename() {
  while true; do
    read -rp "Enter the filename (without extension): " filename
    if [[ -z "$filename" ]]; then
      echo "Please provide a valid filename"
    else
      break
    fi
  done
}

# Create and open file
open_file() {
  local target_directory="$1"
  local filename="$2"
  local full_filename="$target_directory/$filename.md"

  touch "$full_filename"

  timestamp="$(date +"%Y%m%d%H%M%S")"

  {
    echo "# $timestamp"
    echo -en "\n""\n"
  } >>"$full_filename"
  
  vim "+ normal G" "$full_filename"
}

target_directory="$GHREPOS/zet/docs"

get_filename
open_file "$target_directory" "$filename"
