#!/bin/bash

for file in *; do
  # Check if the file ends with ".sh" and is executable
  if [[ "$file" == *.sh && -x "$file" ]]; then
    # Remove the ".sh" extension
    new_name="${file%.sh}"
    mv "$file" "$new_name"
  else
    # Replace whitespace with underscores and remove any character that are
    # not alphanumeric, underscores, or hyphens.
    new_name=$(echo "$file" | tr ' ' _ | sed -E 's/[^[:alnum:]_-]+//g')
    mv "$file" "$new_name"
  fi
done

