#!/bin/bash

for current_file in *; do
  # Check if the file ends with ".sh" and is executable
  if [[ "$current_file" == *.sh && -x "$current_file" ]]; then
    # Remove the ".sh" extension
    new_cleaned_file="${current_file%.sh}"
    mv "$current_file" "$new_cleaned_file"
  else
    # Replace whitespace with underscores and remove any character that are
    # not alphanumeric, underscore, hyphens, or dots.
    new_cleaned_file=$(echo "$current_file" | tr ' ' _ | sed -E 's/[^[:alnum:]_.-]+//g')
    mv "$current_file" "$new_cleaned_file"
  fi
done

