#!/bin/bash

# Change this values for a custom setup
PROJECTS_DIR="$HOME/Projects"
DOTFILES_DIR="$PROJECTS_DIR/dotfiles"
GIT_REPO_URL="git@github.com:lucasherediadv/dotfiles.git"

# Create projects direcotry if it dosen't exist
mkdir -p "$PROJECTS_DIR"

# Set git alias for dotfiles
alias d="/usr/bin/git --git-dir=$DOTFILES_DIR/ --work-tree=$HOME"

# Source repository ignore the folder where you will clone it
# So that you don't create weird recursion problems
echo "$DOTFILES_DIR" >> "$HOME/.gitignore"

# Clone bare git repository inside DOTFILES_DIR
git clone --bare "$GIT_REPO_URL" "$DOTFILES_DIR"

# Checkout the actual content from the bare repository to your $HOME
d checkout

# Handle existing dotfiles
if [ $? = 0 ]; then
    echo "Checked out config.";
else
    echo "Backing up pre-existing dotfiles";
    d checkout 2>&1 | egrep "\s+/." | awk {'print $1'} | xargs -I{} mv {} .config-backup/{}
fi;

# Configure git to ignore untracked files
d config status.showUntrackedFiles no

